name: CP to S3

on:
  push:
    branches:
      - main
    paths:
      - s3bucket/*
  # 手動でも動作させる
  workflow_dispatch:

env:
  BUCKET_NAME: ${{secrets.BUCKET_NAME}}
  AWS_REGION: ${{secrets.AWS_REGION}}

permissions:
  id-token: write
  contents: read

jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repositor
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # S3アクセス権限を持つIAMロール
          role-to-assume: ${{secrets.ROLE_ARN}}
          role-session-name: GitHubActions_s3_cp
          aws-region: ${{env.AWS_REGION}}
      # Upload a file to AWS s3
      - name: CP bucket list to S3
        run: |
          aws s3 cp ./s3buket s3://${{env.BUCKET_NAME}}/ --recursive
          aws s3 ls s3://${{env.BUCKET_NAME}}/

          
  
